[2025-09-10T03:05:20.601+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-10T03:05:20.674+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_models.run_dbt_models scheduled__2025-09-10T02:00:00+00:00 [queued]>
[2025-09-10T03:05:20.704+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_models.run_dbt_models scheduled__2025-09-10T02:00:00+00:00 [queued]>
[2025-09-10T03:05:20.705+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-09-10T03:05:20.767+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-09-10 02:00:00+00:00
[2025-09-10T03:05:20.777+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=3505) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-09-10T03:05:20.778+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_run_models', 'run_dbt_models', 'scheduled__2025-09-10T02:00:00+00:00', '--job-id', '1331', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpyasvwgr4']
[2025-09-10T03:05:20.779+0000] {standard_task_runner.py:91} INFO - Job 1331: Subtask run_dbt_models
[2025-09-10T03:05:20.779+0000] {standard_task_runner.py:64} INFO - Started process 3506 to run task
[2025-09-10T03:05:20.807+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-09-10T03:05:20.911+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_run_models.run_dbt_models scheduled__2025-09-10T02:00:00+00:00 [running]> on host b5ea13053d47
[2025-09-10T03:05:21.155+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_run_models' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-09-10T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-10T02:00:00+00:00'
[2025-09-10T03:05:21.157+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-10T03:05:21.198+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-10T03:05:21.198+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        cd /usr/app &&         dbt run --profiles-dir /usr/app\n        ']
[2025-09-10T03:05:21.225+0000] {subprocess.py:86} INFO - Output:
[2025-09-10T03:05:25.134+0000] {subprocess.py:93} INFO - [0m03:05:25  Running with dbt=1.7.9
[2025-09-10T03:05:25.519+0000] {subprocess.py:93} INFO - [0m03:05:25  Registered adapter: postgres=1.7.9
[2025-09-10T03:05:25.570+0000] {subprocess.py:93} INFO - [0m03:05:25  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-09-10T03:05:25.570+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-09-10T03:05:25.570+0000] {subprocess.py:93} INFO - - models.my_project.sources
[2025-09-10T03:05:25.598+0000] {subprocess.py:93} INFO - [0m03:05:25  Found 15 models, 7 sources, 0 exposures, 0 metrics, 401 macros, 0 groups, 0 semantic models
[2025-09-10T03:05:25.602+0000] {subprocess.py:93} INFO - [0m03:05:25
[2025-09-10T03:05:25.924+0000] {subprocess.py:93} INFO - [0m03:05:25  Concurrency: 4 threads (target='dev')
[2025-09-10T03:05:25.925+0000] {subprocess.py:93} INFO - [0m03:05:25
[2025-09-10T03:05:25.956+0000] {subprocess.py:93} INFO - [0m03:05:25  1 of 15 START sql view model analytics.stg_AOV ................................. [RUN]
[2025-09-10T03:05:25.958+0000] {subprocess.py:93} INFO - [0m03:05:25  2 of 15 START sql view model analytics.stg_order_count_year .................... [RUN]
[2025-09-10T03:05:25.961+0000] {subprocess.py:93} INFO - [0m03:05:25  3 of 15 START sql view model analytics.stg_order_details ....................... [RUN]
[2025-09-10T03:05:25.965+0000] {subprocess.py:93} INFO - [0m03:05:25  4 of 15 START sql view model analytics.stg_order_items ......................... [RUN]
[2025-09-10T03:05:26.573+0000] {subprocess.py:93} INFO - [0m03:05:26  3 of 15 OK created sql view model analytics.stg_order_details .................. [[32mCREATE VIEW[0m in 0.60s]
[2025-09-10T03:05:26.604+0000] {subprocess.py:93} INFO - [0m03:05:26  5 of 15 START sql view model analytics.stg_orders .............................. [RUN]
[2025-09-10T03:05:26.616+0000] {subprocess.py:93} INFO - [0m03:05:26  4 of 15 OK created sql view model analytics.stg_order_items .................... [[32mCREATE VIEW[0m in 0.64s]
[2025-09-10T03:05:26.629+0000] {subprocess.py:93} INFO - [0m03:05:26  1 of 15 OK created sql view model analytics.stg_AOV ............................ [[32mCREATE VIEW[0m in 0.65s]
[2025-09-10T03:05:26.632+0000] {subprocess.py:93} INFO - [0m03:05:26  6 of 15 START sql view model analytics.stg_payments ............................ [RUN]
[2025-09-10T03:05:26.634+0000] {subprocess.py:93} INFO - [0m03:05:26  2 of 15 OK created sql view model analytics.stg_order_count_year ............... [[32mCREATE VIEW[0m in 0.66s]
[2025-09-10T03:05:26.703+0000] {subprocess.py:93} INFO - [0m03:05:26  7 of 15 START sql view model analytics.stg_products ............................ [RUN]
[2025-09-10T03:05:26.715+0000] {subprocess.py:93} INFO - [0m03:05:26  8 of 15 START sql table model analytics.AOV_chek ............................... [RUN]
[2025-09-10T03:05:28.423+0000] {subprocess.py:93} INFO - [0m03:05:28  5 of 15 OK created sql view model analytics.stg_orders ......................... [[32mCREATE VIEW[0m in 1.80s]
[2025-09-10T03:05:28.484+0000] {subprocess.py:93} INFO - [0m03:05:28  9 of 15 START sql table model analytics.order_count_year ....................... [RUN]
[2025-09-10T03:05:28.490+0000] {subprocess.py:93} INFO - [0m03:05:28  6 of 15 OK created sql view model analytics.stg_payments ....................... [[32mCREATE VIEW[0m in 1.82s]
[2025-09-10T03:05:28.491+0000] {subprocess.py:93} INFO - [0m03:05:28  7 of 15 OK created sql view model analytics.stg_products ....................... [[32mCREATE VIEW[0m in 1.76s]
[2025-09-10T03:05:28.569+0000] {subprocess.py:93} INFO - [0m03:05:28  11 of 15 START sql table model analytics.orders_summary ........................ [RUN]
[2025-09-10T03:05:28.570+0000] {subprocess.py:93} INFO - [0m03:05:28  10 of 15 START sql table model analytics.order_count_year+month_diff ........... [RUN]
[2025-09-10T03:05:28.737+0000] {subprocess.py:93} INFO - [0m03:05:28  8 of 15 OK created sql table model analytics.AOV_chek .......................... [[32mSELECT 50[0m in 1.99s]
[2025-09-10T03:05:28.759+0000] {subprocess.py:93} INFO - [0m03:05:28  12 of 15 START sql table model analytics.AVG_AOV_chek .......................... [RUN]
[2025-09-10T03:05:28.983+0000] {subprocess.py:93} INFO - [0m03:05:28  9 of 15 OK created sql table model analytics.order_count_year .................. [[32mSELECT 4[0m in 0.47s]
[2025-09-10T03:05:29.016+0000] {subprocess.py:93} INFO - [0m03:05:29  13 of 15 START sql table model analytics.AOV_EBITDA_COUNT ...................... [RUN]
[2025-09-10T03:05:29.020+0000] {subprocess.py:93} INFO - [0m03:05:29  10 of 15 OK created sql table model analytics.order_count_year+month_diff ...... [[32mSELECT 28[0m in 0.43s]
[2025-09-10T03:05:29.060+0000] {subprocess.py:93} INFO - [0m03:05:29  14 of 15 START sql table model analytics.AOV_category .......................... [RUN]
[2025-09-10T03:05:29.113+0000] {subprocess.py:93} INFO - [0m03:05:29  11 of 15 OK created sql table model analytics.orders_summary ................... [[32mSELECT 10000[0m in 0.54s]
[2025-09-10T03:05:29.120+0000] {subprocess.py:93} INFO - [0m03:05:29  15 of 15 START sql table model analytics.AOV_product_name ...................... [RUN]
[2025-09-10T03:05:29.419+0000] {subprocess.py:93} INFO - [0m03:05:29  13 of 15 ERROR creating sql table model analytics.AOV_EBITDA_COUNT ............. [[31mERROR[0m in 0.38s]
[2025-09-10T03:05:29.430+0000] {subprocess.py:93} INFO - [0m03:05:29  14 of 15 ERROR creating sql table model analytics.AOV_category ................. [[31mERROR[0m in 0.35s]
[2025-09-10T03:05:29.456+0000] {subprocess.py:93} INFO - [0m03:05:29  12 of 15 OK created sql table model analytics.AVG_AOV_chek ..................... [[32mSELECT 16863[0m in 0.68s]
[2025-09-10T03:05:29.459+0000] {subprocess.py:93} INFO - [0m03:05:29  15 of 15 ERROR creating sql table model analytics.AOV_product_name ............. [[31mERROR[0m in 0.33s]
[2025-09-10T03:05:29.497+0000] {subprocess.py:93} INFO - [0m03:05:29
[2025-09-10T03:05:29.499+0000] {subprocess.py:93} INFO - [0m03:05:29  Finished running 7 view models, 8 table models in 0 hours 0 minutes and 3.89 seconds (3.89s).
[2025-09-10T03:05:29.574+0000] {subprocess.py:93} INFO - [0m03:05:29
[2025-09-10T03:05:29.576+0000] {subprocess.py:93} INFO - [0m03:05:29  [31mCompleted with 3 errors and 0 warnings:[0m
[2025-09-10T03:05:29.578+0000] {subprocess.py:93} INFO - [0m03:05:29
[2025-09-10T03:05:29.583+0000] {subprocess.py:93} INFO - [0m03:05:29    Database Error in model AOV_EBITDA_COUNT (models/marts/AOV_EBITDA_COUNT.sql)
[2025-09-10T03:05:29.583+0000] {subprocess.py:93} INFO -   type "avg_order_value" does not exist
[2025-09-10T03:05:29.584+0000] {subprocess.py:93} INFO -   LINE 26: order by avg_order_value
[2025-09-10T03:05:29.584+0000] {subprocess.py:93} INFO -                     ^
[2025-09-10T03:05:29.584+0000] {subprocess.py:93} INFO -   compiled Code at target/run/my_project/models/marts/AOV_EBITDA_COUNT.sql
[2025-09-10T03:05:29.584+0000] {subprocess.py:93} INFO - [0m03:05:29
[2025-09-10T03:05:29.585+0000] {subprocess.py:93} INFO - [0m03:05:29    Database Error in model AOV_category (models/marts/AOV_category.sql)
[2025-09-10T03:05:29.585+0000] {subprocess.py:93} INFO -   type "avg_order_value" does not exist
[2025-09-10T03:05:29.585+0000] {subprocess.py:93} INFO -   LINE 27: order by avg_order_value
[2025-09-10T03:05:29.585+0000] {subprocess.py:93} INFO -                     ^
[2025-09-10T03:05:29.585+0000] {subprocess.py:93} INFO -   compiled Code at target/run/my_project/models/marts/AOV_category.sql
[2025-09-10T03:05:29.586+0000] {subprocess.py:93} INFO - [0m03:05:29
[2025-09-10T03:05:29.588+0000] {subprocess.py:93} INFO - [0m03:05:29    Database Error in model AOV_product_name (models/marts/AOV_product_name.sql)
[2025-09-10T03:05:29.589+0000] {subprocess.py:93} INFO -   type "avg_order_value" does not exist
[2025-09-10T03:05:29.589+0000] {subprocess.py:93} INFO -   LINE 28: order by avg_order_value
[2025-09-10T03:05:29.589+0000] {subprocess.py:93} INFO -                     ^
[2025-09-10T03:05:29.590+0000] {subprocess.py:93} INFO -   compiled Code at target/run/my_project/models/marts/AOV_product_name.sql
[2025-09-10T03:05:29.590+0000] {subprocess.py:93} INFO - [0m03:05:29
[2025-09-10T03:05:29.593+0000] {subprocess.py:93} INFO - [0m03:05:29  Done. PASS=12 WARN=0 ERROR=3 SKIP=0 TOTAL=15
[2025-09-10T03:05:40.200+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-09-10T03:05:40.201+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-10T03:05:40.220+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-10T03:05:40.231+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_run_models, task_id=run_dbt_models, run_id=scheduled__2025-09-10T02:00:00+00:00, execution_date=20250910T020000, start_date=20250910T030520, end_date=20250910T030540
[2025-09-10T03:05:40.254+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1331 for task run_dbt_models (Bash command failed. The command returned a non-zero exit code 1.; 3506)
[2025-09-10T03:05:40.288+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-10T03:05:40.348+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-10T03:05:40.365+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-10T03:11:48.942+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-10T03:11:49.015+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_models.run_dbt_models scheduled__2025-09-10T02:00:00+00:00 [queued]>
[2025-09-10T03:11:49.037+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_models.run_dbt_models scheduled__2025-09-10T02:00:00+00:00 [queued]>
[2025-09-10T03:11:49.038+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-09-10T03:11:49.073+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-09-10 02:00:00+00:00
[2025-09-10T03:11:49.083+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=3547) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-09-10T03:11:49.085+0000] {standard_task_runner.py:64} INFO - Started process 3548 to run task
[2025-09-10T03:11:49.091+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_run_models', 'run_dbt_models', 'scheduled__2025-09-10T02:00:00+00:00', '--job-id', '1334', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpgy790nik']
[2025-09-10T03:11:49.093+0000] {standard_task_runner.py:91} INFO - Job 1334: Subtask run_dbt_models
[2025-09-10T03:11:49.117+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-09-10T03:11:49.192+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_run_models.run_dbt_models scheduled__2025-09-10T02:00:00+00:00 [running]> on host b5ea13053d47
[2025-09-10T03:11:49.412+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_run_models' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-09-10T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-10T02:00:00+00:00'
[2025-09-10T03:11:49.413+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-10T03:11:49.453+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-10T03:11:49.455+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        cd /usr/app &&         dbt run --profiles-dir /usr/app\n        ']
[2025-09-10T03:11:49.471+0000] {subprocess.py:86} INFO - Output:
[2025-09-10T03:11:53.191+0000] {subprocess.py:93} INFO - [0m03:11:53  Running with dbt=1.7.9
[2025-09-10T03:11:53.870+0000] {subprocess.py:93} INFO - [0m03:11:53  Registered adapter: postgres=1.7.9
[2025-09-10T03:11:53.931+0000] {subprocess.py:93} INFO - [0m03:11:53  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-09-10T03:11:53.932+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-09-10T03:11:53.932+0000] {subprocess.py:93} INFO - - models.my_project.sources
[2025-09-10T03:11:53.964+0000] {subprocess.py:93} INFO - [0m03:11:53  Found 15 models, 7 sources, 0 exposures, 0 metrics, 401 macros, 0 groups, 0 semantic models
[2025-09-10T03:11:53.969+0000] {subprocess.py:93} INFO - [0m03:11:53
[2025-09-10T03:11:54.142+0000] {subprocess.py:93} INFO - [0m03:11:54  Concurrency: 4 threads (target='dev')
[2025-09-10T03:11:54.146+0000] {subprocess.py:93} INFO - [0m03:11:54
[2025-09-10T03:11:54.183+0000] {subprocess.py:93} INFO - [0m03:11:54  1 of 15 START sql view model analytics.stg_AOV ................................. [RUN]
[2025-09-10T03:11:54.186+0000] {subprocess.py:93} INFO - [0m03:11:54  2 of 15 START sql view model analytics.stg_order_count_year .................... [RUN]
[2025-09-10T03:11:54.194+0000] {subprocess.py:93} INFO - [0m03:11:54  3 of 15 START sql view model analytics.stg_order_details ....................... [RUN]
[2025-09-10T03:11:54.196+0000] {subprocess.py:93} INFO - [0m03:11:54  4 of 15 START sql view model analytics.stg_order_items ......................... [RUN]
[2025-09-10T03:11:54.749+0000] {subprocess.py:93} INFO - [0m03:11:54  1 of 15 OK created sql view model analytics.stg_AOV ............................ [[32mCREATE VIEW[0m in 0.55s]
[2025-09-10T03:11:54.766+0000] {subprocess.py:93} INFO - [0m03:11:54  5 of 15 START sql view model analytics.stg_orders .............................. [RUN]
[2025-09-10T03:11:54.775+0000] {subprocess.py:93} INFO - [0m03:11:54  4 of 15 OK created sql view model analytics.stg_order_items .................... [[32mCREATE VIEW[0m in 0.57s]
[2025-09-10T03:11:54.777+0000] {subprocess.py:93} INFO - [0m03:11:54  3 of 15 OK created sql view model analytics.stg_order_details .................. [[32mCREATE VIEW[0m in 0.57s]
[2025-09-10T03:11:54.793+0000] {subprocess.py:93} INFO - [0m03:11:54  2 of 15 OK created sql view model analytics.stg_order_count_year ............... [[32mCREATE VIEW[0m in 0.59s]
[2025-09-10T03:11:54.801+0000] {subprocess.py:93} INFO - [0m03:11:54  6 of 15 START sql view model analytics.stg_payments ............................ [RUN]
[2025-09-10T03:11:54.830+0000] {subprocess.py:93} INFO - [0m03:11:54  8 of 15 START sql table model analytics.AOV_chek ............................... [RUN]
[2025-09-10T03:11:54.832+0000] {subprocess.py:93} INFO - [0m03:11:54  7 of 15 START sql view model analytics.stg_products ............................ [RUN]
[2025-09-10T03:11:55.165+0000] {subprocess.py:93} INFO - [0m03:11:55  5 of 15 OK created sql view model analytics.stg_orders ......................... [[32mCREATE VIEW[0m in 0.39s]
[2025-09-10T03:11:55.202+0000] {subprocess.py:93} INFO - [0m03:11:55  9 of 15 START sql table model analytics.order_count_year ....................... [RUN]
[2025-09-10T03:11:55.253+0000] {subprocess.py:93} INFO - [0m03:11:55  6 of 15 OK created sql view model analytics.stg_payments ....................... [[32mCREATE VIEW[0m in 0.40s]
[2025-09-10T03:11:55.283+0000] {subprocess.py:93} INFO - [0m03:11:55  10 of 15 START sql table model analytics.order_count_year+month_diff ........... [RUN]
[2025-09-10T03:11:55.284+0000] {subprocess.py:93} INFO - [0m03:11:55  7 of 15 OK created sql view model analytics.stg_products ....................... [[32mCREATE VIEW[0m in 0.44s]
[2025-09-10T03:11:55.301+0000] {subprocess.py:93} INFO - [0m03:11:55  8 of 15 OK created sql table model analytics.AOV_chek .......................... [[32mSELECT 50[0m in 0.45s]
[2025-09-10T03:11:55.310+0000] {subprocess.py:93} INFO - [0m03:11:55  11 of 15 START sql table model analytics.orders_summary ........................ [RUN]
[2025-09-10T03:11:55.319+0000] {subprocess.py:93} INFO - [0m03:11:55  12 of 15 START sql table model analytics.AVG_AOV_chek .......................... [RUN]
[2025-09-10T03:11:55.659+0000] {subprocess.py:93} INFO - [0m03:11:55  9 of 15 OK created sql table model analytics.order_count_year .................. [[32mSELECT 4[0m in 0.43s]
[2025-09-10T03:11:55.711+0000] {subprocess.py:93} INFO - [0m03:11:55  13 of 15 START sql table model analytics.AOV_EBITDA_COUNT ...................... [RUN]
[2025-09-10T03:11:55.714+0000] {subprocess.py:93} INFO - [0m03:11:55  10 of 15 OK created sql table model analytics.order_count_year+month_diff ...... [[32mSELECT 28[0m in 0.41s]
[2025-09-10T03:11:55.735+0000] {subprocess.py:93} INFO - [0m03:11:55  14 of 15 START sql table model analytics.AOV_category .......................... [RUN]
[2025-09-10T03:11:55.922+0000] {subprocess.py:93} INFO - [0m03:11:55  11 of 15 OK created sql table model analytics.orders_summary ................... [[32mSELECT 10000[0m in 0.60s]
[2025-09-10T03:11:55.947+0000] {subprocess.py:93} INFO - [0m03:11:55  15 of 15 START sql table model analytics.AOV_product_name ...................... [RUN]
[2025-09-10T03:11:56.095+0000] {subprocess.py:93} INFO - [0m03:11:56  12 of 15 OK created sql table model analytics.AVG_AOV_chek ..................... [[32mSELECT 16863[0m in 0.76s]
[2025-09-10T03:11:56.142+0000] {subprocess.py:93} INFO - [0m03:11:56  14 of 15 ERROR creating sql table model analytics.AOV_category ................. [[31mERROR[0m in 0.38s]
[2025-09-10T03:11:56.146+0000] {subprocess.py:93} INFO - [0m03:11:56  13 of 15 ERROR creating sql table model analytics.AOV_EBITDA_COUNT ............. [[31mERROR[0m in 0.42s]
[2025-09-10T03:11:56.189+0000] {subprocess.py:93} INFO - [0m03:11:56  15 of 15 ERROR creating sql table model analytics.AOV_product_name ............. [[31mERROR[0m in 0.23s]
[2025-09-10T03:11:56.216+0000] {subprocess.py:93} INFO - [0m03:11:56
[2025-09-10T03:11:56.217+0000] {subprocess.py:93} INFO - [0m03:11:56  Finished running 7 view models, 8 table models in 0 hours 0 minutes and 2.25 seconds (2.25s).
[2025-09-10T03:11:56.232+0000] {subprocess.py:93} INFO - [0m03:11:56
[2025-09-10T03:11:56.233+0000] {subprocess.py:93} INFO - [0m03:11:56  [31mCompleted with 3 errors and 0 warnings:[0m
[2025-09-10T03:11:56.233+0000] {subprocess.py:93} INFO - [0m03:11:56
[2025-09-10T03:11:56.234+0000] {subprocess.py:93} INFO - [0m03:11:56    Database Error in model AOV_category (models/marts/AOV_category.sql)
[2025-09-10T03:11:56.234+0000] {subprocess.py:93} INFO -   type "avg_order_value" does not exist
[2025-09-10T03:11:56.235+0000] {subprocess.py:93} INFO -   LINE 27: order by avg_order_value
[2025-09-10T03:11:56.235+0000] {subprocess.py:93} INFO -                     ^
[2025-09-10T03:11:56.236+0000] {subprocess.py:93} INFO -   compiled Code at target/run/my_project/models/marts/AOV_category.sql
[2025-09-10T03:11:56.239+0000] {subprocess.py:93} INFO - [0m03:11:56
[2025-09-10T03:11:56.241+0000] {subprocess.py:93} INFO - [0m03:11:56    Database Error in model AOV_EBITDA_COUNT (models/marts/AOV_EBITDA_COUNT.sql)
[2025-09-10T03:11:56.242+0000] {subprocess.py:93} INFO -   type "avg_order_value" does not exist
[2025-09-10T03:11:56.242+0000] {subprocess.py:93} INFO -   LINE 26: order by avg_order_value
[2025-09-10T03:11:56.242+0000] {subprocess.py:93} INFO -                     ^
[2025-09-10T03:11:56.245+0000] {subprocess.py:93} INFO -   compiled Code at target/run/my_project/models/marts/AOV_EBITDA_COUNT.sql
[2025-09-10T03:11:56.246+0000] {subprocess.py:93} INFO - [0m03:11:56
[2025-09-10T03:11:56.246+0000] {subprocess.py:93} INFO - [0m03:11:56    Database Error in model AOV_product_name (models/marts/AOV_product_name.sql)
[2025-09-10T03:11:56.246+0000] {subprocess.py:93} INFO -   type "avg_order_value" does not exist
[2025-09-10T03:11:56.246+0000] {subprocess.py:93} INFO -   LINE 28: order by avg_order_value
[2025-09-10T03:11:56.246+0000] {subprocess.py:93} INFO -                     ^
[2025-09-10T03:11:56.246+0000] {subprocess.py:93} INFO -   compiled Code at target/run/my_project/models/marts/AOV_product_name.sql
[2025-09-10T03:11:56.247+0000] {subprocess.py:93} INFO - [0m03:11:56
[2025-09-10T03:11:56.247+0000] {subprocess.py:93} INFO - [0m03:11:56  Done. PASS=12 WARN=0 ERROR=3 SKIP=0 TOTAL=15
[2025-09-10T03:12:06.640+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-09-10T03:12:06.641+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-10T03:12:06.665+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-10T03:12:06.677+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_run_models, task_id=run_dbt_models, run_id=scheduled__2025-09-10T02:00:00+00:00, execution_date=20250910T020000, start_date=20250910T031149, end_date=20250910T031206
[2025-09-10T03:12:06.712+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1334 for task run_dbt_models (Bash command failed. The command returned a non-zero exit code 1.; 3548)
[2025-09-10T03:12:06.745+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-10T03:12:06.807+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-10T03:12:06.815+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-10T03:23:01.330+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-10T03:23:01.361+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_models.run_dbt_models scheduled__2025-09-10T02:00:00+00:00 [queued]>
[2025-09-10T03:23:01.371+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_models.run_dbt_models scheduled__2025-09-10T02:00:00+00:00 [queued]>
[2025-09-10T03:23:01.371+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-09-10T03:23:01.391+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-09-10 02:00:00+00:00
[2025-09-10T03:23:01.398+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=3625) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-09-10T03:23:01.399+0000] {standard_task_runner.py:64} INFO - Started process 3626 to run task
[2025-09-10T03:23:01.405+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_run_models', 'run_dbt_models', 'scheduled__2025-09-10T02:00:00+00:00', '--job-id', '1340', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpydfgiop5']
[2025-09-10T03:23:01.407+0000] {standard_task_runner.py:91} INFO - Job 1340: Subtask run_dbt_models
[2025-09-10T03:23:01.438+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-09-10T03:23:01.499+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_run_models.run_dbt_models scheduled__2025-09-10T02:00:00+00:00 [running]> on host b5ea13053d47
[2025-09-10T03:23:01.690+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_run_models' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-09-10T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-10T02:00:00+00:00'
[2025-09-10T03:23:01.693+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-10T03:23:01.735+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-10T03:23:01.736+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        cd /usr/app &&         dbt run --profiles-dir /usr/app\n        ']
[2025-09-10T03:23:01.752+0000] {subprocess.py:86} INFO - Output:
[2025-09-10T03:23:05.931+0000] {subprocess.py:93} INFO - [0m03:23:05  Running with dbt=1.7.9
[2025-09-10T03:23:06.323+0000] {subprocess.py:93} INFO - [0m03:23:06  Registered adapter: postgres=1.7.9
[2025-09-10T03:23:06.375+0000] {subprocess.py:93} INFO - [0m03:23:06  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-09-10T03:23:06.376+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-09-10T03:23:06.376+0000] {subprocess.py:93} INFO - - models.my_project.sources
[2025-09-10T03:23:06.403+0000] {subprocess.py:93} INFO - [0m03:23:06  Found 15 models, 7 sources, 0 exposures, 0 metrics, 401 macros, 0 groups, 0 semantic models
[2025-09-10T03:23:06.407+0000] {subprocess.py:93} INFO - [0m03:23:06
[2025-09-10T03:23:06.768+0000] {subprocess.py:93} INFO - [0m03:23:06  Concurrency: 4 threads (target='dev')
[2025-09-10T03:23:06.771+0000] {subprocess.py:93} INFO - [0m03:23:06
[2025-09-10T03:23:06.805+0000] {subprocess.py:93} INFO - [0m03:23:06  1 of 15 START sql view model analytics.stg_AOV ................................. [RUN]
[2025-09-10T03:23:06.810+0000] {subprocess.py:93} INFO - [0m03:23:06  2 of 15 START sql view model analytics.stg_order_count_year .................... [RUN]
[2025-09-10T03:23:06.814+0000] {subprocess.py:93} INFO - [0m03:23:06  3 of 15 START sql view model analytics.stg_order_details ....................... [RUN]
[2025-09-10T03:23:06.815+0000] {subprocess.py:93} INFO - [0m03:23:06  4 of 15 START sql view model analytics.stg_order_items ......................... [RUN]
[2025-09-10T03:23:07.675+0000] {subprocess.py:93} INFO - [0m03:23:07  3 of 15 OK created sql view model analytics.stg_order_details .................. [[32mCREATE VIEW[0m in 0.81s]
[2025-09-10T03:23:07.701+0000] {subprocess.py:93} INFO - [0m03:23:07  4 of 15 OK created sql view model analytics.stg_order_items .................... [[32mCREATE VIEW[0m in 0.86s]
[2025-09-10T03:23:07.706+0000] {subprocess.py:93} INFO - [0m03:23:07  1 of 15 OK created sql view model analytics.stg_AOV ............................ [[32mCREATE VIEW[0m in 0.88s]
[2025-09-10T03:23:07.710+0000] {subprocess.py:93} INFO - [0m03:23:07  2 of 15 OK created sql view model analytics.stg_order_count_year ............... [[32mCREATE VIEW[0m in 0.88s]
[2025-09-10T03:23:07.717+0000] {subprocess.py:93} INFO - [0m03:23:07  5 of 15 START sql view model analytics.stg_orders .............................. [RUN]
[2025-09-10T03:23:07.727+0000] {subprocess.py:93} INFO - [0m03:23:07  7 of 15 START sql view model analytics.stg_products ............................ [RUN]
[2025-09-10T03:23:07.735+0000] {subprocess.py:93} INFO - [0m03:23:07  6 of 15 START sql view model analytics.stg_payments ............................ [RUN]
[2025-09-10T03:23:07.761+0000] {subprocess.py:93} INFO - [0m03:23:07  8 of 15 START sql table model analytics.AOV_chek ............................... [RUN]
[2025-09-10T03:23:08.235+0000] {subprocess.py:93} INFO - [0m03:23:08  7 of 15 OK created sql view model analytics.stg_products ....................... [[32mCREATE VIEW[0m in 0.45s]
[2025-09-10T03:23:08.281+0000] {subprocess.py:93} INFO - [0m03:23:08  9 of 15 START sql table model analytics.order_count_year ....................... [RUN]
[2025-09-10T03:23:08.290+0000] {subprocess.py:93} INFO - [0m03:23:08  5 of 15 OK created sql view model analytics.stg_orders ......................... [[32mCREATE VIEW[0m in 0.54s]
[2025-09-10T03:23:08.333+0000] {subprocess.py:93} INFO - [0m03:23:08  10 of 15 START sql table model analytics.order_count_year+month_diff ........... [RUN]
[2025-09-10T03:23:08.342+0000] {subprocess.py:93} INFO - [0m03:23:08  8 of 15 OK created sql table model analytics.AOV_chek .......................... [[32mSELECT 50[0m in 0.56s]
[2025-09-10T03:23:08.357+0000] {subprocess.py:93} INFO - [0m03:23:08  6 of 15 OK created sql view model analytics.stg_payments ....................... [[32mCREATE VIEW[0m in 0.60s]
[2025-09-10T03:23:08.371+0000] {subprocess.py:93} INFO - [0m03:23:08  11 of 15 START sql table model analytics.orders_summary ........................ [RUN]
[2025-09-10T03:23:08.386+0000] {subprocess.py:93} INFO - [0m03:23:08  12 of 15 START sql table model analytics.AOV_EBITDA_COUNT ...................... [RUN]
[2025-09-10T03:23:08.629+0000] {subprocess.py:93} INFO - [0m03:23:08  12 of 15 ERROR creating sql table model analytics.AOV_EBITDA_COUNT ............. [[31mERROR[0m in 0.21s]
[2025-09-10T03:23:08.662+0000] {subprocess.py:93} INFO - [0m03:23:08  13 of 15 START sql table model analytics.AOV_category .......................... [RUN]
[2025-09-10T03:23:08.781+0000] {subprocess.py:93} INFO - [0m03:23:08  9 of 15 OK created sql table model analytics.order_count_year .................. [[32mSELECT 4[0m in 0.46s]
[2025-09-10T03:23:08.814+0000] {subprocess.py:93} INFO - [0m03:23:08  14 of 15 START sql table model analytics.AOV_product_name ...................... [RUN]
[2025-09-10T03:23:08.830+0000] {subprocess.py:93} INFO - [0m03:23:08  10 of 15 OK created sql table model analytics.order_count_year+month_diff ...... [[32mSELECT 28[0m in 0.49s]
[2025-09-10T03:23:08.872+0000] {subprocess.py:93} INFO - [0m03:23:08  15 of 15 START sql table model analytics.AVG_AOV_chek .......................... [RUN]
[2025-09-10T03:23:08.882+0000] {subprocess.py:93} INFO - [0m03:23:08  11 of 15 OK created sql table model analytics.orders_summary ................... [[32mSELECT 10000[0m in 0.50s]
[2025-09-10T03:23:08.917+0000] {subprocess.py:93} INFO - [0m03:23:08  13 of 15 ERROR creating sql table model analytics.AOV_category ................. [[31mERROR[0m in 0.24s]
[2025-09-10T03:23:08.966+0000] {subprocess.py:93} INFO - [0m03:23:08  14 of 15 ERROR creating sql table model analytics.AOV_product_name ............. [[31mERROR[0m in 0.15s]
[2025-09-10T03:23:09.358+0000] {subprocess.py:93} INFO - [0m03:23:09  15 of 15 OK created sql table model analytics.AVG_AOV_chek ..................... [[32mSELECT 16863[0m in 0.47s]
[2025-09-10T03:23:09.405+0000] {subprocess.py:93} INFO - [0m03:23:09
[2025-09-10T03:23:09.406+0000] {subprocess.py:93} INFO - [0m03:23:09  Finished running 7 view models, 8 table models in 0 hours 0 minutes and 3.00 seconds (3.00s).
[2025-09-10T03:23:09.425+0000] {subprocess.py:93} INFO - [0m03:23:09
[2025-09-10T03:23:09.426+0000] {subprocess.py:93} INFO - [0m03:23:09  [31mCompleted with 3 errors and 0 warnings:[0m
[2025-09-10T03:23:09.426+0000] {subprocess.py:93} INFO - [0m03:23:09
[2025-09-10T03:23:09.426+0000] {subprocess.py:93} INFO - [0m03:23:09    Database Error in model AOV_EBITDA_COUNT (models/marts/AOV_EBITDA_COUNT.sql)
[2025-09-10T03:23:09.427+0000] {subprocess.py:93} INFO -   type "avg_order_value" does not exist
[2025-09-10T03:23:09.427+0000] {subprocess.py:93} INFO -   LINE 26: order by avg_order_value
[2025-09-10T03:23:09.427+0000] {subprocess.py:93} INFO -                     ^
[2025-09-10T03:23:09.428+0000] {subprocess.py:93} INFO -   compiled Code at target/run/my_project/models/marts/AOV_EBITDA_COUNT.sql
[2025-09-10T03:23:09.428+0000] {subprocess.py:93} INFO - [0m03:23:09
[2025-09-10T03:23:09.429+0000] {subprocess.py:93} INFO - [0m03:23:09    Database Error in model AOV_category (models/marts/AOV_category.sql)
[2025-09-10T03:23:09.429+0000] {subprocess.py:93} INFO -   type "avg_order_value" does not exist
[2025-09-10T03:23:09.429+0000] {subprocess.py:93} INFO -   LINE 29: order by avg_order_value
[2025-09-10T03:23:09.430+0000] {subprocess.py:93} INFO -                     ^
[2025-09-10T03:23:09.431+0000] {subprocess.py:93} INFO -   compiled Code at target/run/my_project/models/marts/AOV_category.sql
[2025-09-10T03:23:09.432+0000] {subprocess.py:93} INFO - [0m03:23:09
[2025-09-10T03:23:09.432+0000] {subprocess.py:93} INFO - [0m03:23:09    Database Error in model AOV_product_name (models/marts/AOV_product_name.sql)
[2025-09-10T03:23:09.432+0000] {subprocess.py:93} INFO -   type "avg_order_value" does not exist
[2025-09-10T03:23:09.433+0000] {subprocess.py:93} INFO -   LINE 30: order by avg_order_value
[2025-09-10T03:23:09.433+0000] {subprocess.py:93} INFO -                     ^
[2025-09-10T03:23:09.433+0000] {subprocess.py:93} INFO -   compiled Code at target/run/my_project/models/marts/AOV_product_name.sql
[2025-09-10T03:23:09.434+0000] {subprocess.py:93} INFO - [0m03:23:09
[2025-09-10T03:23:09.434+0000] {subprocess.py:93} INFO - [0m03:23:09  Done. PASS=12 WARN=0 ERROR=3 SKIP=0 TOTAL=15
[2025-09-10T03:23:19.959+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-09-10T03:23:19.960+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-10T03:23:19.992+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-10T03:23:20.004+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_run_models, task_id=run_dbt_models, run_id=scheduled__2025-09-10T02:00:00+00:00, execution_date=20250910T020000, start_date=20250910T032301, end_date=20250910T032320
[2025-09-10T03:23:20.048+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1340 for task run_dbt_models (Bash command failed. The command returned a non-zero exit code 1.; 3626)
[2025-09-10T03:23:20.079+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-10T03:23:20.121+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-10T03:23:20.126+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-10T03:35:53.923+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-10T03:35:54.007+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_models.run_dbt_models scheduled__2025-09-10T02:00:00+00:00 [queued]>
[2025-09-10T03:35:54.035+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_models.run_dbt_models scheduled__2025-09-10T02:00:00+00:00 [queued]>
[2025-09-10T03:35:54.035+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-09-10T03:35:54.072+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-09-10 02:00:00+00:00
[2025-09-10T03:35:54.087+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=3699) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-09-10T03:35:54.089+0000] {standard_task_runner.py:64} INFO - Started process 3700 to run task
[2025-09-10T03:35:54.093+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_run_models', 'run_dbt_models', 'scheduled__2025-09-10T02:00:00+00:00', '--job-id', '1344', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmps0v_wv60']
[2025-09-10T03:35:54.095+0000] {standard_task_runner.py:91} INFO - Job 1344: Subtask run_dbt_models
[2025-09-10T03:35:54.135+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-09-10T03:35:54.226+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_run_models.run_dbt_models scheduled__2025-09-10T02:00:00+00:00 [running]> on host b5ea13053d47
[2025-09-10T03:35:54.437+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_run_models' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-09-10T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-10T02:00:00+00:00'
[2025-09-10T03:35:54.439+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-10T03:35:54.487+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-10T03:35:54.489+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        cd /usr/app &&         dbt run --profiles-dir /usr/app\n        ']
[2025-09-10T03:35:54.510+0000] {subprocess.py:86} INFO - Output:
[2025-09-10T03:35:58.857+0000] {subprocess.py:93} INFO - [0m03:35:58  Running with dbt=1.7.9
[2025-09-10T03:35:59.682+0000] {subprocess.py:93} INFO - [0m03:35:59  Registered adapter: postgres=1.7.9
[2025-09-10T03:35:59.758+0000] {subprocess.py:93} INFO - [0m03:35:59  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-09-10T03:35:59.758+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-09-10T03:35:59.758+0000] {subprocess.py:93} INFO - - models.my_project.sources
[2025-09-10T03:35:59.798+0000] {subprocess.py:93} INFO - [0m03:35:59  Found 15 models, 7 sources, 0 exposures, 0 metrics, 401 macros, 0 groups, 0 semantic models
[2025-09-10T03:35:59.805+0000] {subprocess.py:93} INFO - [0m03:35:59
[2025-09-10T03:36:00.189+0000] {subprocess.py:93} INFO - [0m03:36:00  Concurrency: 4 threads (target='dev')
[2025-09-10T03:36:00.190+0000] {subprocess.py:93} INFO - [0m03:36:00
[2025-09-10T03:36:00.265+0000] {subprocess.py:93} INFO - [0m03:36:00  1 of 15 START sql view model analytics.stg_AOV ................................. [RUN]
[2025-09-10T03:36:00.266+0000] {subprocess.py:93} INFO - [0m03:36:00  2 of 15 START sql view model analytics.stg_order_count_year .................... [RUN]
[2025-09-10T03:36:00.272+0000] {subprocess.py:93} INFO - [0m03:36:00  3 of 15 START sql view model analytics.stg_order_details ....................... [RUN]
[2025-09-10T03:36:00.324+0000] {subprocess.py:93} INFO - [0m03:36:00  4 of 15 START sql view model analytics.stg_order_items ......................... [RUN]
[2025-09-10T03:36:01.080+0000] {subprocess.py:93} INFO - [0m03:36:01  3 of 15 OK created sql view model analytics.stg_order_details .................. [[32mCREATE VIEW[0m in 0.80s]
[2025-09-10T03:36:01.080+0000] {subprocess.py:93} INFO - [0m03:36:01  2 of 15 OK created sql view model analytics.stg_order_count_year ............... [[32mCREATE VIEW[0m in 0.80s]
[2025-09-10T03:36:01.092+0000] {subprocess.py:93} INFO - [0m03:36:01  4 of 15 OK created sql view model analytics.stg_order_items .................... [[32mCREATE VIEW[0m in 0.72s]
[2025-09-10T03:36:01.100+0000] {subprocess.py:93} INFO - [0m03:36:01  7 of 15 START sql view model analytics.stg_products ............................ [RUN]
[2025-09-10T03:36:01.100+0000] {subprocess.py:93} INFO - [0m03:36:01  5 of 15 START sql view model analytics.stg_orders .............................. [RUN]
[2025-09-10T03:36:01.100+0000] {subprocess.py:93} INFO - [0m03:36:01  6 of 15 START sql view model analytics.stg_payments ............................ [RUN]
[2025-09-10T03:36:01.128+0000] {subprocess.py:93} INFO - [0m03:36:01  1 of 15 OK created sql view model analytics.stg_AOV ............................ [[32mCREATE VIEW[0m in 0.85s]
[2025-09-10T03:36:01.171+0000] {subprocess.py:93} INFO - [0m03:36:01  8 of 15 START sql table model analytics.order_count_year ....................... [RUN]
[2025-09-10T03:36:01.660+0000] {subprocess.py:93} INFO - [0m03:36:01  6 of 15 OK created sql view model analytics.stg_payments ....................... [[32mCREATE VIEW[0m in 0.54s]
[2025-09-10T03:36:01.675+0000] {subprocess.py:93} INFO - [0m03:36:01  5 of 15 OK created sql view model analytics.stg_orders ......................... [[32mCREATE VIEW[0m in 0.56s]
[2025-09-10T03:36:01.684+0000] {subprocess.py:93} INFO - [0m03:36:01  10 of 15 START sql table model analytics.AOV_chek .............................. [RUN]
[2025-09-10T03:36:01.686+0000] {subprocess.py:93} INFO - [0m03:36:01  9 of 15 START sql table model analytics.order_count_year+month_diff ............ [RUN]
[2025-09-10T03:36:01.720+0000] {subprocess.py:93} INFO - [0m03:36:01  7 of 15 OK created sql view model analytics.stg_products ....................... [[32mCREATE VIEW[0m in 0.60s]
[2025-09-10T03:36:01.755+0000] {subprocess.py:93} INFO - [0m03:36:01  11 of 15 START sql table model analytics.AVG_AOV_chek .......................... [RUN]
[2025-09-10T03:36:02.025+0000] {subprocess.py:93} INFO - [0m03:36:02  8 of 15 OK created sql table model analytics.order_count_year .................. [[32mSELECT 4[0m in 0.84s]
[2025-09-10T03:36:02.058+0000] {subprocess.py:93} INFO - [0m03:36:02  12 of 15 START sql table model analytics.orders_summary ........................ [RUN]
[2025-09-10T03:36:02.128+0000] {subprocess.py:93} INFO - [0m03:36:02  9 of 15 OK created sql table model analytics.order_count_year+month_diff ....... [[32mSELECT 28[0m in 0.41s]
[2025-09-10T03:36:02.196+0000] {subprocess.py:93} INFO - [0m03:36:02  13 of 15 START sql table model analytics.AOV_EBITDA_COUNT ...................... [RUN]
[2025-09-10T03:36:02.211+0000] {subprocess.py:93} INFO - [0m03:36:02  10 of 15 OK created sql table model analytics.AOV_chek ......................... [[32mSELECT 50[0m in 0.51s]
[2025-09-10T03:36:02.219+0000] {subprocess.py:93} INFO - [0m03:36:02  14 of 15 START sql table model analytics.AOV_category .......................... [RUN]
[2025-09-10T03:36:02.370+0000] {subprocess.py:93} INFO - [0m03:36:02  11 of 15 OK created sql table model analytics.AVG_AOV_chek ..................... [[32mSELECT 16863[0m in 0.59s]
[2025-09-10T03:36:02.542+0000] {subprocess.py:93} INFO - [0m03:36:02  15 of 15 START sql table model analytics.AOV_product_name ...................... [RUN]
[2025-09-10T03:36:02.855+0000] {subprocess.py:93} INFO - [0m03:36:02  12 of 15 OK created sql table model analytics.orders_summary ................... [[32mSELECT 10000[0m in 0.79s]
[2025-09-10T03:36:02.870+0000] {subprocess.py:93} INFO - [0m03:36:02  13 of 15 OK created sql table model analytics.AOV_EBITDA_COUNT ................. [[32mSELECT 1[0m in 0.66s]
[2025-09-10T03:36:02.917+0000] {subprocess.py:93} INFO - [0m03:36:02  14 of 15 OK created sql table model analytics.AOV_category ..................... [[32mSELECT 4[0m in 0.67s]
[2025-09-10T03:36:03.117+0000] {subprocess.py:93} INFO - [0m03:36:03  15 of 15 OK created sql table model analytics.AOV_product_name ................. [[32mSELECT 50[0m in 0.55s]
[2025-09-10T03:36:03.144+0000] {subprocess.py:93} INFO - [0m03:36:03
[2025-09-10T03:36:03.145+0000] {subprocess.py:93} INFO - [0m03:36:03  Finished running 7 view models, 8 table models in 0 hours 0 minutes and 3.34 seconds (3.34s).
[2025-09-10T03:36:03.160+0000] {subprocess.py:93} INFO - [0m03:36:03
[2025-09-10T03:36:03.161+0000] {subprocess.py:93} INFO - [0m03:36:03  [32mCompleted successfully[0m
[2025-09-10T03:36:03.169+0000] {subprocess.py:93} INFO - [0m03:36:03
[2025-09-10T03:36:03.170+0000] {subprocess.py:93} INFO - [0m03:36:03  Done. PASS=15 WARN=0 ERROR=0 SKIP=0 TOTAL=15
[2025-09-10T03:36:13.619+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-09-10T03:36:13.619+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-10T03:36:13.661+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dbt_run_models, task_id=run_dbt_models, run_id=scheduled__2025-09-10T02:00:00+00:00, execution_date=20250910T020000, start_date=20250910T033554, end_date=20250910T033613
[2025-09-10T03:36:13.712+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-10T03:36:13.742+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-10T03:36:13.746+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
