[2025-08-27T16:00:02.222+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-27T16:00:02.254+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: import_csv_to_postgres.wait_for_generation scheduled__2025-08-27T08:00:00+00:00 [queued]>
[2025-08-27T16:00:02.271+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: import_csv_to_postgres.wait_for_generation scheduled__2025-08-27T08:00:00+00:00 [queued]>
[2025-08-27T16:00:02.272+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-27T16:00:02.330+0000] {taskinstance.py:2330} INFO - Executing <Task(ExternalTaskSensor): wait_for_generation> on 2025-08-27 08:00:00+00:00
[2025-08-27T16:00:02.342+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1465) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-27T16:00:02.343+0000] {standard_task_runner.py:64} INFO - Started process 1467 to run task
[2025-08-27T16:00:02.347+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'import_csv_to_postgres', 'wait_for_generation', 'scheduled__2025-08-27T08:00:00+00:00', '--job-id', '679', '--raw', '--subdir', 'DAGS_FOLDER/csv_to_postgres_dag.py', '--cfg-path', '/tmp/tmp17w18t25']
[2025-08-27T16:00:02.355+0000] {standard_task_runner.py:91} INFO - Job 679: Subtask wait_for_generation
[2025-08-27T16:00:02.382+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-08-27T16:00:02.460+0000] {task_command.py:426} INFO - Running <TaskInstance: import_csv_to_postgres.wait_for_generation scheduled__2025-08-27T08:00:00+00:00 [running]> on host b5ea13053d47
[2025-08-27T16:00:02.691+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='import_csv_to_postgres' AIRFLOW_CTX_TASK_ID='wait_for_generation' AIRFLOW_CTX_EXECUTION_DATE='2025-08-27T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-27T08:00:00+00:00'
[2025-08-27T16:00:02.694+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-27T16:00:02.728+0000] {baseoperator.py:400} WARNING - ExternalTaskSensor.execute cannot be called outside TaskInstance!
[2025-08-27T16:00:02.729+0000] {external_task.py:274} INFO - Poking for DAG 'daily_generate_orders' on 2025-08-27T08:00:00+00:00 ... 
[2025-08-27T16:00:02.730+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py:79: DeprecationWarning: This method is deprecated and will be removed in future.
  return func(*args, session=session, **kwargs)

[2025-08-27T16:01:02.749+0000] {external_task.py:274} INFO - Poking for DAG 'daily_generate_orders' on 2025-08-27T08:00:00+00:00 ... 
[2025-08-27T16:02:02.767+0000] {external_task.py:274} INFO - Poking for DAG 'daily_generate_orders' on 2025-08-27T08:00:00+00:00 ... 
[2025-08-27T16:03:02.776+0000] {external_task.py:274} INFO - Poking for DAG 'daily_generate_orders' on 2025-08-27T08:00:00+00:00 ... 
[2025-08-27T16:04:02.787+0000] {external_task.py:274} INFO - Poking for DAG 'daily_generate_orders' on 2025-08-27T08:00:00+00:00 ... 
[2025-08-27T16:05:02.803+0000] {external_task.py:274} INFO - Poking for DAG 'daily_generate_orders' on 2025-08-27T08:00:00+00:00 ... 
[2025-08-27T16:06:02.823+0000] {external_task.py:274} INFO - Poking for DAG 'daily_generate_orders' on 2025-08-27T08:00:00+00:00 ... 
[2025-08-27T16:07:02.833+0000] {external_task.py:274} INFO - Poking for DAG 'daily_generate_orders' on 2025-08-27T08:00:00+00:00 ... 
[2025-08-27T16:08:02.909+0000] {external_task.py:274} INFO - Poking for DAG 'daily_generate_orders' on 2025-08-27T08:00:00+00:00 ... 
[2025-08-27T16:09:02.917+0000] {external_task.py:274} INFO - Poking for DAG 'daily_generate_orders' on 2025-08-27T08:00:00+00:00 ... 
[2025-08-27T16:10:02.924+0000] {external_task.py:274} INFO - Poking for DAG 'daily_generate_orders' on 2025-08-27T08:00:00+00:00 ... 
[2025-08-27T16:10:02.931+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-27T16:10:02.931+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/external_task.py", line 348, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 281, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 600.2021326310933 seconds exceeds the specified timeout of 600.0.
[2025-08-27T16:10:02.941+0000] {taskinstance.py:1206} INFO - Immediate failure requested. Marking task as FAILED. dag_id=import_csv_to_postgres, task_id=wait_for_generation, run_id=scheduled__2025-08-27T08:00:00+00:00, execution_date=20250827T080000, start_date=20250827T160002, end_date=20250827T161002
[2025-08-27T16:10:02.956+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 679 for task wait_for_generation (Sensor has timed out; run duration of 600.2021326310933 seconds exceeds the specified timeout of 600.0.; 1467)
[2025-08-27T16:10:02.982+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-08-27T16:10:02.999+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-27T16:10:03.003+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-08-27T16:10:45.758+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-27T16:10:45.797+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: import_csv_to_postgres.wait_for_generation scheduled__2025-08-27T08:00:00+00:00 [queued]>
[2025-08-27T16:10:45.816+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: import_csv_to_postgres.wait_for_generation scheduled__2025-08-27T08:00:00+00:00 [queued]>
[2025-08-27T16:10:45.816+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-27T16:10:45.832+0000] {taskinstance.py:2330} INFO - Executing <Task(ExternalTaskSensor): wait_for_generation> on 2025-08-27 08:00:00+00:00
[2025-08-27T16:10:45.840+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1471) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-27T16:10:45.841+0000] {standard_task_runner.py:64} INFO - Started process 1473 to run task
[2025-08-27T16:10:45.847+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'import_csv_to_postgres', 'wait_for_generation', 'scheduled__2025-08-27T08:00:00+00:00', '--job-id', '681', '--raw', '--subdir', 'DAGS_FOLDER/csv_to_postgres_dag.py', '--cfg-path', '/tmp/tmpn17avdig']
[2025-08-27T16:10:45.852+0000] {standard_task_runner.py:91} INFO - Job 681: Subtask wait_for_generation
[2025-08-27T16:10:45.876+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-08-27T16:10:45.942+0000] {task_command.py:426} INFO - Running <TaskInstance: import_csv_to_postgres.wait_for_generation scheduled__2025-08-27T08:00:00+00:00 [running]> on host b5ea13053d47
[2025-08-27T16:10:46.133+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='import_csv_to_postgres' AIRFLOW_CTX_TASK_ID='wait_for_generation' AIRFLOW_CTX_EXECUTION_DATE='2025-08-27T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-27T08:00:00+00:00'
[2025-08-27T16:10:46.136+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-27T16:10:46.166+0000] {baseoperator.py:400} WARNING - ExternalTaskSensor.execute cannot be called outside TaskInstance!
[2025-08-27T16:10:46.179+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-27T16:10:46.180+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/external_task.py", line 348, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 264, in execute
    raise e
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 246, in execute
    poke_return = self.poke(context)
                  ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/external_task.py", line 255, in poke
    serialized_dttm_filter = ",".join(dt.isoformat() for dt in dttm_filter)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/external_task.py", line 255, in <genexpr>
    serialized_dttm_filter = ",".join(dt.isoformat() for dt in dttm_filter)
                                      ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'isoformat'
[2025-08-27T16:10:46.191+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=import_csv_to_postgres, task_id=wait_for_generation, run_id=scheduled__2025-08-27T08:00:00+00:00, execution_date=20250827T080000, start_date=20250827T161045, end_date=20250827T161046
[2025-08-27T16:10:46.204+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 681 for task wait_for_generation ('NoneType' object has no attribute 'isoformat'; 1473)
[2025-08-27T16:10:46.256+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-08-27T16:10:46.288+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-27T16:10:46.294+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-08-27T16:30:45.385+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-27T16:30:45.497+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: import_csv_to_postgres.wait_for_generation scheduled__2025-08-27T08:00:00+00:00 [queued]>
[2025-08-27T16:30:45.537+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: import_csv_to_postgres.wait_for_generation scheduled__2025-08-27T08:00:00+00:00 [queued]>
[2025-08-27T16:30:45.538+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-27T16:30:45.606+0000] {taskinstance.py:2330} INFO - Executing <Task(ExternalTaskSensor): wait_for_generation> on 2025-08-27 08:00:00+00:00
[2025-08-27T16:30:45.632+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1497) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-27T16:30:45.635+0000] {standard_task_runner.py:64} INFO - Started process 1499 to run task
[2025-08-27T16:30:45.638+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'import_csv_to_postgres', 'wait_for_generation', 'scheduled__2025-08-27T08:00:00+00:00', '--job-id', '683', '--raw', '--subdir', 'DAGS_FOLDER/csv_to_postgres_dag.py', '--cfg-path', '/tmp/tmpydsf68os']
[2025-08-27T16:30:45.647+0000] {standard_task_runner.py:91} INFO - Job 683: Subtask wait_for_generation
[2025-08-27T16:30:45.696+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-08-27T16:30:45.838+0000] {task_command.py:426} INFO - Running <TaskInstance: import_csv_to_postgres.wait_for_generation scheduled__2025-08-27T08:00:00+00:00 [running]> on host b5ea13053d47
[2025-08-27T16:30:46.258+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='import_csv_to_postgres' AIRFLOW_CTX_TASK_ID='wait_for_generation' AIRFLOW_CTX_EXECUTION_DATE='2025-08-27T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-27T08:00:00+00:00'
[2025-08-27T16:30:46.262+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-27T16:30:46.336+0000] {baseoperator.py:400} WARNING - ExternalTaskSensor.execute cannot be called outside TaskInstance!
[2025-08-27T16:30:46.405+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-27T16:30:46.408+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/external_task.py", line 348, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 264, in execute
    raise e
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 246, in execute
    poke_return = self.poke(context)
                  ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/external_task.py", line 255, in poke
    serialized_dttm_filter = ",".join(dt.isoformat() for dt in dttm_filter)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/external_task.py", line 255, in <genexpr>
    serialized_dttm_filter = ",".join(dt.isoformat() for dt in dttm_filter)
                                      ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'isoformat'
[2025-08-27T16:30:46.457+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=import_csv_to_postgres, task_id=wait_for_generation, run_id=scheduled__2025-08-27T08:00:00+00:00, execution_date=20250827T080000, start_date=20250827T163045, end_date=20250827T163046
[2025-08-27T16:30:46.557+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 683 for task wait_for_generation ('NoneType' object has no attribute 'isoformat'; 1499)
[2025-08-27T16:30:46.583+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-08-27T16:30:46.725+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-27T16:30:46.744+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
