[2025-09-04T05:00:19.261+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-04T05:00:19.335+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_models.test_dbt_models scheduled__2025-09-04T04:00:00+00:00 [queued]>
[2025-09-04T05:00:19.353+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_models.test_dbt_models scheduled__2025-09-04T04:00:00+00:00 [queued]>
[2025-09-04T05:00:19.354+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-04T05:00:19.388+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): test_dbt_models> on 2025-09-04 04:00:00+00:00
[2025-09-04T05:00:19.396+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=321) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-09-04T05:00:19.398+0000] {standard_task_runner.py:64} INFO - Started process 322 to run task
[2025-09-04T05:00:19.401+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_run_models', 'test_dbt_models', 'scheduled__2025-09-04T04:00:00+00:00', '--job-id', '988', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpc7qz6pms']
[2025-09-04T05:00:19.402+0000] {standard_task_runner.py:91} INFO - Job 988: Subtask test_dbt_models
[2025-09-04T05:00:19.426+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-09-04T05:00:19.491+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_run_models.test_dbt_models scheduled__2025-09-04T04:00:00+00:00 [running]> on host b5ea13053d47
[2025-09-04T05:00:19.705+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_run_models' AIRFLOW_CTX_TASK_ID='test_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-09-04T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-04T04:00:00+00:00'
[2025-09-04T05:00:19.707+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-04T05:00:19.749+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-04T05:00:19.750+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        cd /usr/app &&         dbt test --profiles-dir /usr/app\n        ']
[2025-09-04T05:00:19.770+0000] {subprocess.py:86} INFO - Output:
[2025-09-04T05:00:23.571+0000] {subprocess.py:93} INFO - [0m05:00:23  Running with dbt=1.7.9
[2025-09-04T05:00:23.952+0000] {subprocess.py:93} INFO - [0m05:00:23  Registered adapter: postgres=1.7.9
[2025-09-04T05:00:23.998+0000] {subprocess.py:93} INFO - [0m05:00:23  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-09-04T05:00:23.998+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-09-04T05:00:23.999+0000] {subprocess.py:93} INFO - - models.my_project.sources
[2025-09-04T05:00:24.022+0000] {subprocess.py:93} INFO - [0m05:00:24  Found 5 models, 7 sources, 0 exposures, 0 metrics, 401 macros, 0 groups, 0 semantic models
[2025-09-04T05:00:24.025+0000] {subprocess.py:93} INFO - [0m05:00:24
[2025-09-04T05:00:24.026+0000] {subprocess.py:93} INFO - [0m05:00:24  Nothing to do. Try checking your model configs and model specification args
[2025-09-04T05:00:34.550+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-09-04T05:00:34.552+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-04T05:00:34.605+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dbt_run_models, task_id=test_dbt_models, run_id=scheduled__2025-09-04T04:00:00+00:00, execution_date=20250904T040000, start_date=20250904T050019, end_date=20250904T050034
[2025-09-04T05:00:34.640+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-04T05:00:34.678+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-04T05:00:34.681+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
