[2025-09-03T08:00:25.683+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-03T08:00:25.737+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_models.test_dbt_models scheduled__2025-09-03T07:00:00+00:00 [queued]>
[2025-09-03T08:00:25.750+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_models.test_dbt_models scheduled__2025-09-03T07:00:00+00:00 [queued]>
[2025-09-03T08:00:25.751+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-03T08:00:25.774+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): test_dbt_models> on 2025-09-03 07:00:00+00:00
[2025-09-03T08:00:25.782+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=85) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-09-03T08:00:25.783+0000] {standard_task_runner.py:64} INFO - Started process 86 to run task
[2025-09-03T08:00:25.787+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_run_models', 'test_dbt_models', 'scheduled__2025-09-03T07:00:00+00:00', '--job-id', '940', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpenwcx90q']
[2025-09-03T08:00:25.789+0000] {standard_task_runner.py:91} INFO - Job 940: Subtask test_dbt_models
[2025-09-03T08:00:25.823+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-09-03T08:00:25.881+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_run_models.test_dbt_models scheduled__2025-09-03T07:00:00+00:00 [running]> on host b5ea13053d47
[2025-09-03T08:00:26.013+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_run_models' AIRFLOW_CTX_TASK_ID='test_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-09-03T07:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-03T07:00:00+00:00'
[2025-09-03T08:00:26.014+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-03T08:00:26.045+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-03T08:00:26.046+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        cd /usr/app &&         dbt test --profiles-dir /usr/app\n        ']
[2025-09-03T08:00:26.066+0000] {subprocess.py:86} INFO - Output:
[2025-09-03T08:00:33.961+0000] {subprocess.py:93} INFO - [0m08:00:33  Running with dbt=1.7.9
[2025-09-03T08:00:34.483+0000] {subprocess.py:93} INFO - [0m08:00:34  Registered adapter: postgres=1.7.9
[2025-09-03T08:00:34.549+0000] {subprocess.py:93} INFO - [0m08:00:34  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-09-03T08:00:34.550+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-09-03T08:00:34.550+0000] {subprocess.py:93} INFO - - models.my_project.sources
[2025-09-03T08:00:34.586+0000] {subprocess.py:93} INFO - [0m08:00:34  Found 5 models, 7 sources, 0 exposures, 0 metrics, 401 macros, 0 groups, 0 semantic models
[2025-09-03T08:00:34.590+0000] {subprocess.py:93} INFO - [0m08:00:34
[2025-09-03T08:00:34.591+0000] {subprocess.py:93} INFO - [0m08:00:34  Nothing to do. Try checking your model configs and model specification args
[2025-09-03T08:00:45.113+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-09-03T08:00:45.115+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-03T08:00:45.169+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dbt_run_models, task_id=test_dbt_models, run_id=scheduled__2025-09-03T07:00:00+00:00, execution_date=20250903T070000, start_date=20250903T080025, end_date=20250903T080045
[2025-09-03T08:00:45.223+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-03T08:00:45.259+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-03T08:00:45.269+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
